# -*- coding: utf-8 -*-
"""AULA 1- PANDAS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NAbiZfnm4UUwve2T04Dkl6FzYbCxy5ny
"""

#IMPORTANDO A BIBLIOTECA PANDA

import pandas as pd

df = pd.read_csv("/content/Gapminder.csv", error_bad_lines= False, sep=";")



df= df.rename(columns= {"country": "Pais", "continent": "Continente", "year": "Ano", "lifeExp": "Expectativa de vida", "pop": "População", "gdpPercap": "PIB"})

#Visualizando as  primeiras linhas

df.head(5)

df.head()

# MOSTRA TOTAL DE LINHAS E COLUNAS 
df.shape

#mostras as colunas 
df.columns

#mostra os tipos de dados em cada coluna 
df.dtypes

#mostra o final da coluna
df.tail()

#mostras as 15 ultimas colunas. voce pode escolher o numero dentro
df.tail(15)

#Descreve os dados em formato de média final dos valores da tabela toda
df.describe()

pdf["Continente"].unique()

Oceania= df.loc[df["Continente"]== "Oceania"]
Oceania.head()

df.groupby("Continente")["Pais"].nunique()

#Saber a expectativa média por ano

df.groupby("Ano")["Expectativa de vida"].mean ()



#Saber a média ----> usa .mean
df["PIB"].mean()

#Saber  a soma ---> .sum()
df["PIB"].sum()