# -*- coding: utf-8 -*-
"""PANDA 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Phag99hXToCXMfV4JlWWSzDLmHcgZ9-

PLANILHAS DO EXCEL **negrito**
"""

import pandas as pd

#Leitura dos arquivos

df1=pd.read_excel("Aracaju.xlsx")
df2=pd.read_excel("Natal.xlsx")
df3=pd.read_excel("Fortaleza.xlsx")
df4=pd.read_excel("Recife.xlsx")
df5=pd.read_excel("Salvador.xlsx")

#juntando os arquivos

df=pd.concat([df1,df2,df3,df4,df5])

df.head()

df.tail()

df.sample(5)

#Verificando os tipos de dado de cada coluna
df.dtypes

#Alterando o tipo de dados da coluna LOJAID

df["LojaID"]=df["LojaID"].astype("object")

df.dtypes

df.head()

#Consultar linhas com valor faltante

df.isnull().sum()

#Criando colunas novas

df["Receita"] = df ["Vendas"].mul(df["Qtde"])

df.head()

df [ "Receita"]. max()

df ["Receita"].min()

#mostra as linhas com as maiores receitas
df.nlargest(3,"Receita")

#Mostra menos receita

df.nsmallest(3,"Receita")



"""**Trabahando com Datas**"""

#Transformando a coluna de data em tipo inteiro 
df["Data"]= df["Data"].astype("int64")

df.dtypes

#Transformando coluna data em data 

df["Data"] = pd.to_datetime(df["Data"])

#Agrupar por ano

df.groupby(df["Data"].dt.year)["Receita"].sum()

#Criando nova coluna com o ano

df ["Ano_Venda"] = df ["Data"].dt.year

df.sample(5)

#Grafico de barras

df["LojaID"].value_counts(ascending=False)

